<a href="https://colab.research.google.com/github/ShashikanthKungulwar/CV_practice/blob/main/mnist_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.datasets import mnist

In [ ]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
x_train = x_train/255
x_test = x_test/255
x_train = x_train.reshape(-1,28,28,1)
x_test = x_test.reshape(-1,28,28,1)

input_shape = (28,28,1) # in case of pytoch it will be (1,28,28)

In [ ]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [ ]:
# label preprocessing
num_classes = 10
print(y_train[:10])

y_train = tf.keras.utils.to_categorical(y_train,10)
y_test = tf.keras.utils.to_categorical(y_test,10)

print(y_train[:10])

[5 0 4 1 9 2 1 3 1 4]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
x_train.shape

(60000, 28, 28, 1)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,Flatten,MaxPooling2D,Dense

model = Sequential()

model.add(Conv2D(32,kernel_size=(3,3),activation="relu",input_shape=(28,28,1),padding="same"))
model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Conv2D(64,kernel_size=(3,3),activation="relu",padding="same"))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Flatten())
model.add(Dense(64,activation="relu"))
model.add(Dense(10,activation="softmax"))


model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 3136)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │       200,768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 220,234 (860.29 KB)

 Trainable params: 220,234 (860.29 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:

model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint

modelcheckpoint = ModelCheckpoint(
    filepath="model.keras",
    save_best_only=True,
    verbose=1
)

model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,verbose=2,shuffle=True,batch_size=64,callbacks=[modelcheckpoint])

Epoch 1/10

Epoch 1: val_loss improved from None to 0.05496, saving model to model.weights.best.keras

Epoch 1: finished saving model to model.weights.best.keras
938/938 - 11s - 12ms/step - accuracy: 0.9517 - loss: 0.1613 - val_accuracy: 0.9818 - val_loss: 0.0550
Epoch 2/10

Epoch 2: val_loss improved from 0.05496 to 0.03902, saving model to model.weights.best.keras

Epoch 2: finished saving model to model.weights.best.keras
938/938 - 4s - 4ms/step - accuracy: 0.9847 - loss: 0.0491 - val_accuracy: 0.9865 - val_loss: 0.0390
Epoch 3/10

Epoch 3: val_loss improved from 0.03902 to 0.03221, saving model to model.weights.best.keras

Epoch 3: finished saving model to model.weights.best.keras
938/938 - 3s - 3ms/step - accuracy: 0.9893 - loss: 0.0337 - val_accuracy: 0.9886 - val_loss: 0.0322
Epoch 4/10

Epoch 4: val_loss did not improve from 0.03221
938/938 - 3s - 3ms/step - accuracy: 0.9919 - loss: 0.0254 - val_accuracy: 0.9876 - val_loss: 0.0374
Epoch 5/10

Epoch 5: val_loss improved from 0.0

In [ ]:
model.load_weights("model.weights.best.keras")

In [ ]:
score = model.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9906 - loss: 0.0286


In [ ]:
score

[0.028638819232583046, 0.9905999898910522]